config/routes.rb
Rails.application.routes.draw do
  resources :userrequests
  resources :news
  devise_for :users
  root 'news#index'
  resources :users
  resources :userrequests do
    member do
      get 'news_response'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :news
  has_many :userrequests

  enum role: [:standard, :premium, :admin]

  after_initialize do
    if self.new_record?
      self.role ||= :standard
    end
  end
end

app/models/userrequest.rb
class Userrequest < ApplicationRecord
  belongs_to :user

  after_initialize do
    if self.new_record?
      self.status ||= :panding
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :role, :password)}
    #devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private
  def user_not_authorized
    flash[:notice] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ edit new update destroy ]

  # GET /news or /news.json
  def index
    @news = News.all
  end

  # GET /news/1 or /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
    authorize @news
  end

  # GET /news/1/edit
  def edit
    authorize @news
  end

  # POST /news or /news.json
  def create
    @news = News.new(news_params.merge(user_id: current_user.id))
    #authorize @news
    respond_to do |format|
      if @news.save
        NewsMailer.with(news: @news).admin_email.deliver_later
        format.html { redirect_to @news, notice: "News was successfully created." }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1 or /news/1.json
  def update
    respond_to do |format|
      authorize @news
      if @news.update(news_params)
        format.html { redirect_to @news, notice: "News was successfully updated." }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1 or /news/1.json
  def destroy
    authorize @news
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: "News was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def news_params
      params.require(:news).permit(:name, current_user.id)
      #authorize @news
    end
end

app/controllers/userrequests_controller.rb
class UserrequestsController < ApplicationController
  before_action :set_userrequest, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ index edit new update destroy show ]

  # GET /userrequests or /userrequests.json
  def index
    @userrequests = Userrequest.all
  end

  # GET /userrequests/1 or /userrequests/1.json
  def show
    @userrequest = Userrequest.find(params[:id])
  end

  # GET /userrequests/new
  def new
    @userrequest = Userrequest.new
  end

  # GET /userrequests/1/edit
  def edit
  end

  def news_response
    @userrequest = Userrequest.find(params[:id]).update(status: "approved")
    flash[:notice] = "You approved this news request."
    p "news response"
    p @userrequest
    @userrequest = Userrequest.find(params[:id])
    p @userrequest
    UserrequestsMailer.with(userrequest: @userrequest).approve_notification.deliver_later
  end

  # POST /userrequests or /userrequests.json
  def create
    @userrequest = Userrequest.new(userrequest_params.merge(user_id: current_user.id, admin: User.where(role: "admin").order("RANDOM()").limit(1).ids[0]))

    respond_to do |format|
      if @userrequest.save
        UserrequestsMailer.with(userrequest: @userrequest).admin_mail.deliver_later
        UserrequestsMailer.with(userrequest: @userrequest).user_email.deliver_later
        format.html { redirect_to @userrequest, notice: "Userrequest was successfully created." }
        format.json { render :show, status: :created, location: @userrequest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @userrequest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /userrequests/1 or /userrequests/1.json
  def update
    respond_to do |format|
      if @userrequest.update(userrequest_params)
        format.html { redirect_to @userrequest, notice: "Userrequest was successfully updated." }
        format.json { render :show, status: :ok, location: @userrequest }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @userrequest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userrequests/1 or /userrequests/1.json
  def destroy
    @userrequest.destroy
    respond_to do |format|
      format.html { redirect_to userrequests_url, notice: "Userrequest was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userrequest
      @userrequest = Userrequest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def userrequest_params
      params.require(:userrequest).permit(:news, :purpose, current_user.id, :admin)
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  #def create
  #  super
  #end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[ index show edit new update destroy ]

  def new
    @users = User.new
  end

  def index
    authorize current_user
    @users = User.all
    p "user jain"
    p @users
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/userrequests_helper.rb
module UserrequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def admin_name(user)
    User.find(user).username
  end

  def admin_user(user)
    User.find(user)
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevisePractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/news/_form.html.erb
<%= form_with(model: news) do |form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
        <% news.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.username %></strong>.
  User role <strong> <%= current_user.role %> </strong>.
  <%= link_to 'sign out', destroy_user_session_path, method: :delete %> |
  <%= link_to 'edit profile', edit_user_registration_path %> |
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %> |
<% end %>
<%= link_to 'news request', new_userrequest_path %> |
<% if current_user.try(:admin?) %>
  <%= link_to 'response', userrequests_url %>
<% else %>
  <%= link_to 'status', userrequests_url %>
<% end %>

<h1>News</h1>

<table>
  <thead>
    <tr>
      <th>News</th>
      <th>User name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.name %></td>
        <td><%= news.user.username%></td>
        <td><%= link_to 'Show', news %></td>
        <% if (current_user.try(:premium?) && current_user == news.user ) || current_user.try(:admin?) %>
          <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <% end %>
        <% if current_user.try(:admin?) %>
          <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.try(:premium?) || current_user.try(:admin?)  %>
  <%= link_to 'New News', new_news_path %> |
<% end %>
<% if current_user.try(:admin?) %>
  <%= link_to 'User list', users_url %>
<% end %>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @news.name %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>

app/views/userrequests/_form.html.erb
<%= form_with(model: userrequest) do |form| %>
  <% if userrequest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(userrequest.errors.count, "error") %> prohibited this userrequest from being saved:</h2>

      <ul>
        <% userrequest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :news %>
    <%= form.text_field :news %>
  </div>

  <div class="field">
    <%= form.label :purpose %>
    <%= form.text_field :purpose %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/userrequests/edit.html.erb
<h1>Editing Userrequest</h1>

<%= render 'form', userrequest: @userrequest %>

<%= link_to 'Show', @userrequest %> |
<%= link_to 'Back', userrequests_path %>

app/views/userrequests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Userrequests</h1>

<table>
  <thead>
    <tr>
      <th>News</th>
      <th>Purpose</th>
      <th>Status</th>
      <th>Admin</th>
      <% if current_user.try(:admin?) %>
        <th>User</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userrequests.each do |userrequest| %>
      <tr>
        <% if (current_user.try(:admin?) && current_user == admin_user(userrequest.admin)) || current_user == userrequest.user %>
          <td><%= userrequest.news %></td>
          <td><%= userrequest.purpose %></td>
          <td><%= userrequest.status%></td>
          <td><%= admin_name(userrequest.admin) %></td>
          <% if (current_user.try(:admin?) && current_user == admin_user(userrequest.admin)) %>
            <td><%= userrequest.user.username %></td>
            <td><%= link_to 'approve request', news_response_userrequest_path(userrequest.id) %></td>
            <td><%= link_to 'Destroy', userrequest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
          <td><%= link_to 'Show', userrequest %></td>
          <% if (current_user.try(:premium?) && current_user == userrequest.user ) || current_user.try(:admin?) %>
            <td><%= link_to 'Edit', edit_userrequest_path(userrequest) %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Userrequest', new_userrequest_path %>

app/views/userrequests/new.html.erb
<h1>New Userrequest</h1>

<%= render 'form', userrequest: @userrequest %>

<%= link_to 'Back', userrequests_path %>

app/views/userrequests/news_response.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'home', root_path %>

app/views/userrequests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>News:</strong>
  <%= @userrequest.news %>
</p>

<p>
  <strong>Purpose:</strong>
  <%= @userrequest.purpose %>
</p>

<p>
  <strong>Status:</strong>
    <%= @userrequest.status %>
</p>

<p>
  <strong>Admin:</strong>
  <%= admin_name(@userrequest.admin) %>
</p>

<p>
  <strong>User:</strong>
    <%= @userrequest.user.username %>
</p>

<%= link_to 'Edit', edit_userrequest_path(@userrequest) %> |
<%= link_to 'Back', userrequests_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>User Name</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.username %></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %> |
<%= link_to 'back', root_path %>